cache:
  paths:
    - vendor/

before_script:
  - apt-get -yqq update && apt-get -yq upgrade
  - apt-get -yqq install zip unzip git
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

stages:
  - test

phpunit:
  image: php:5.6
  stage: test
  script:
    - vendor/bin/phpunit
